# * this method should use python -m to make sure the hydra config is loaded correctly
# hydra config
hydra:
  run:
    dir: ${paths.log_path}
  job:
    chdir: false

# Path
paths:
  pt_path: /workspace/data/pt
  video_path: /workspace/data/side_raw # this is raw data path, with left and right side view.
  log_path: logs/vggt/${now:%Y-%m-%d}/${now:%H-%M-%S}

# Model
model:
  ckpt_path: /workspace/code/ckpt/pretrained_h36m_detectron_coco.bin

visualize:
  save_video: true
  plot_3d: true
  plot_2d: true
  plot_skeleton: true
  plot_skeleton_3d: true

infer:
  conf_thres: 50.0
  prediction_mode: "Depthmap and Camera Branch"
  keep_frames: true
  export_ply: true
  voxel_size: 0.0
  random_sample: null
  gpu: 1

runtime:
  verbose: true
  run_multi_view: true
  run_single_view: true
  num_workers: 4
  debug: false

dataset:
  recursive: false
